name: release CI
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark as Pre-release'
        required: false
        type: boolean
      publish:
        description: 'Publish release'
        required: false
        type: boolean
        default: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up dependencies
        run: |
            sudo apt-get install -y make gcc g++ libboost-all-dev libtorrent-rasterbar-dev libcairo2-dev
          
      - name: Build
        run: |
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: xitorrent-x86_64
          path: xitorrent

      - name: Set version
        run: |
          make appversion
          echo "version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ inputs.prerelease }}
          files: ./xitorrent
          automatic_release_tag: v${{ env.version }}
